
ALTER TABLE RECEIPT
ADD IS_SMS_SENT nvarchar(10) NULL

UPDATE RECEIPT SET IS_SMS_SENT = 'Y' WHERE RE_DATE < ''

ALTER TABLE PAYMENT
ADD IS_SMS_SENT nvarchar(10) NULL

UPDATE PAYMENT SET IS_SMS_SENT = 'Y' WHERE PA_DATE < ''

ALTER TABLE FT_DTAIL
ADD IS_SMS_SENT nvarchar(10) NULL

UPDATE FT_DTAIL SET IS_SMS_SENT = 'Y' WHERE WHEN1 < ''

ALTER TABLE XMODIFIED_RECEIPT
ADD IS_SMS_SENT nvarchar(10) NULL


ALTER TABLE XMODIFIED_PAYMENT
ADD IS_SMS_SENT nvarchar(10) NULL


ALTER TABLE XMODIFIED_FT_DTAIL
ADD IS_SMS_SENT nvarchar(10) NULL


ALTER TABLE XDELETED_RECEIPT
ADD IS_SMS_SENT nvarchar(10) NULL


ALTER TABLE XDELETED_PAYMENT
ADD IS_SMS_SENT nvarchar(10) NULL


ALTER TABLE XDELETED_FT_DTAIL
ADD IS_SMS_SENT nvarchar(10) NULL




CREATE TABLE SMS_RECEIVED
(idAuto int IDENTITY(1,1) NOT NULL,
received_id int NOT NULL,
phone_no nvarchar(255) NULL,
keyword nvarchar(255) NULL,
account_no nvarchar(255) NULL,
password nvarchar(255) NULL,
received_date datetime NULL)
					
				
					
					

CREATE TABLE SMS_SENT
(idAuto int IDENTITY(1,1) NOT NULL,
msg_type nvarchar(256) NULL,
received_id int NULL,
recipient nvarchar(256) NULL,
message nvarchar(256) NULL,
sent_date datetime NULL,
msg_status nvarchar (256) NULL)



					
CREATE VIEW VIEW_SMS_JURNAL AS SELECT FT_DTAIL.FD_CODE, FT_DTAIL.FD_VALUE, FT_DTAIL.FD_RN, FT_DTAIL.FD_TYPE, FT_DTAIL.FD_TOMEMBER, 
FT_DTAIL.FD_TOEXPENCE, INCOME_EXPENCE.IE_SUB_TYPE, INCOME_EXPENCE.IE_CODE, FT_DTAIL.WHEN1, FT_DTAIL.IS_SMS_SENT, CUSTOMER.CM_DESC, CUSTOMER.CM_NAME_ENGLISH
CUSTOMER.CM_TELE, CUSTOMER.CM_OFFICE_NO, CUST_CATEGORY.CC_CODE, CUST_CATEGORY.CC_NAME, CUST_CATEGORY_MAIN.CC_CODE AS CENTER_CODE, 
CUST_CATEGORY_MAIN.CC_NAME AS CENTER_NAME, FFROM_TTO.FT_DATE FROM FT_DTAIL INNER JOIN INCOME_EXPENCE_SUB ON 
FT_DTAIL.FD_TOEXPENCE = INCOME_EXPENCE_SUB.IE_CODE INNER JOIN INCOME_EXPENCE ON 
INCOME_EXPENCE_SUB.IE_MAIN = INCOME_EXPENCE.IE_CODE INNER JOIN CUST_CATEGORY_MAIN INNER JOIN CUST_CATEGORY ON 
CUST_CATEGORY_MAIN.CC_CODE = CUST_CATEGORY.CC_MAIN INNER JOIN CUSTOMER ON CUST_CATEGORY.CC_CODE = CUSTOMER.CM_CATEGORY ON 
FT_DTAIL.FD_TOMEMBER = CUSTOMER.CM_CODE INNER JOIN FFROM_TTO ON FT_DTAIL.FD_CODE = FFROM_TTO.FT_CODE WHERE
(FT_DTAIL.IS_SMS_SENT IS NULL) OR (FT_DTAIL.IS_SMS_SENT = 'N')
					
					
CREATE VIEW [VIEW_CATEGORYMAIN_CATEGORYSUB_CUSTOMER]
AS
SELECT     CUST_CATEGORY_MAIN.CC_CODE AS cluster_code, CUST_CATEGORY_MAIN.CC_NAME AS cluster_name, 
                      CUST_CATEGORY_MAIN.CC_OFFICER AS mfo, CUST_CATEGORY.CC_CODE AS small_group_code, 
                      CUST_CATEGORY.CC_NAME AS small_group_name, CUSTOMER.CM_CODE, CUSTOMER.CM_DESC, CUSTOMER.CM_ID, 
                      CUSTOMER.CM_BDATE, CUSTOMER.CM_ADD1, CUSTOMER.CM_ADD2, CUSTOMER.CM_ADD3, CUSTOMER.CM_ADD4, 
                      CUSTOMER.CM_TELE, CUSTOMER.CM_FLAG, CUSTOMER.CM_OFFICE_NO
FROM         CUSTOMER LEFT OUTER JOIN
                      CUST_CATEGORY ON CUSTOMER.CM_CATEGORY = CUST_CATEGORY.CC_CODE LEFT OUTER JOIN
                      CUST_CATEGORY_MAIN ON CUST_CATEGORY.CC_MAIN = CUST_CATEGORY_MAIN.CC_CODE






-- SMS COUNT -------------------------------------------------------------------
CREATE TABLE SMS_COUNT(
	ID_AUTO int IDENTITY(1,1) NOT NULL,
	ID int NULL,
	SMS_TYPE nchar(10) NULL,
	SMS_COUNT int NULL,
	SENT_DATETIME datetime NULL)