/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iroshan.com.smsserver.view;

import iroshan.Company_Profile;
import iroshan.com.common.derby.view.Setting;
import iroshan.com.common.utility.WindowLocation;
import iroshan.com.smsserver.service.MySMSServer;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import org.smslib.SMSLibException;
import org.smslib.Service;

/**
 *
 * @author Iroshan
 */
public class ApplicationDesktop extends javax.swing.JFrame {

    public static ApplicationDesktop appDesktop;
//    public static JDesktopPane jDesktopPane;
    private MySMSServer mySMSServer;

    /**
     * Creates new form ApplicationDesktop
     */
    public ApplicationDesktop() {

        initComponents();
        appDesktop = this;
        WindowLocation.setMaiximizedFrame(this);
        onLoad();
        this.setTitle(Company_Profile.getVersion());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton14 = new javax.swing.JButton();
        jDesktopPane = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        appDesktop_Status_Panel = new javax.swing.JPanel();
        appDesktop_Status_but = new javax.swing.JToggleButton();
        appDesktop_Status_lbl = new javax.swing.JLabel();
        lblCompanyName = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iroshan/com/smsserver/img/Devices.png"))); // NOI18N
        jButton14.setText("Early Settlement");
        jButton14.setBorder(null);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMS_20200430_2");
        setIconImage(new ImageIcon(getClass().getResource("Messaging.png")).getImage());

        jDesktopPane.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iroshan/com/smsserver/img/Personalize.png"))); // NOI18N
        jButton6.setText("<HTML>CUSTOM MESSAGE</HTML>      ");
        jButton6.setBorder(null);
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iroshan/com/smsserver/img/Live Messenger alt 2.png"))); // NOI18N
        jButton13.setText("<HTML>MESSAGE TO <br> MEMBER</HTML>");
        jButton13.setBorder(null);
        jButton13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jButton13.setVisible(true);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iroshan/com/smsserver/img/Live Messenger alt 2.png"))); // NOI18N
        jButton9.setText("<HTML>MESSAGE TO <br>MULTICLUSTER MEMBER</HTML>");
        jButton9.setBorder(null);
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jButton9.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jButton13)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton6.setVisible(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iroshan/com/smsserver/img/Hulu.png"))); // NOI18N
        jButton11.setText("HISTORY - SEND ");
        jButton11.setBorder(null);
        jButton11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jButton11.setVisible(false);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iroshan/com/smsserver/img/Hulu Plus.png"))); // NOI18N
        jButton10.setText("HISTORY - RECEIVED   ");
        jButton10.setBorder(null);
        jButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jButton10.setVisible(false);

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iroshan/com/smsserver/img/Video - Google Docs.png"))); // NOI18N
        jButton12.setText("<HTML>MESSAGE <br>MONITOR</HTML>");
        jButton12.setBorder(null);
        jButton12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jButton12.setVisible(false);

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton15.setText("Message Counter");
        jButton15.setBorder(null);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton15.setVisible(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iroshan/com/smsserver/img/Desktop Folder.png"))); // NOI18N
        jButton3.setText("<HTML>OUTSTANDING<HTML>");
        jButton3.setBorder(null);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setVisible(false);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iroshan/com/smsserver/img/Devices.png"))); // NOI18N
        jButton4.setText("DUE                     ");
        jButton4.setBorder(null);
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setVisible(false);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iroshan/com/smsserver/img/Bookmarks alt.png"))); // NOI18N
        jButton5.setText("ARREARS           ");
        jButton5.setBorder(null);
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setVisible(false);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iroshan/com/smsserver/img/Bank-icon.png"))); // NOI18N
        jButton8.setText("Disbursed Loan ");
        jButton8.setBorder(null);
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jButton8.setVisible(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iroshan/com/smsserver/img/Documents.png"))); // NOI18N
        jButton1.setText("RECEIPT   ");
        jButton1.setBorder(null);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iroshan/com/smsserver/img/Documents Library.png"))); // NOI18N
        jButton2.setText("PAYMENT ");
        jButton2.setBorder(null);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setVisible(true);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iroshan/com/smsserver/img/Documents Library.png"))); // NOI18N
        jButton7.setText("JURNAL    ");
        jButton7.setBorder(null);
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(258, Short.MAX_VALUE))
        );

        appDesktop_Status_Panel.setBackground(new java.awt.Color(153, 0, 0));

        appDesktop_Status_but.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        appDesktop_Status_but.setSelected(true);
        appDesktop_Status_but.setText("CONNECT");
        appDesktop_Status_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appDesktop_Status_butActionPerformed(evt);
            }
        });

        appDesktop_Status_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        appDesktop_Status_lbl.setForeground(new java.awt.Color(255, 255, 255));
        appDesktop_Status_lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        appDesktop_Status_lbl.setText("STOPPED");

        javax.swing.GroupLayout appDesktop_Status_PanelLayout = new javax.swing.GroupLayout(appDesktop_Status_Panel);
        appDesktop_Status_Panel.setLayout(appDesktop_Status_PanelLayout);
        appDesktop_Status_PanelLayout.setHorizontalGroup(
            appDesktop_Status_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appDesktop_Status_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(appDesktop_Status_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(appDesktop_Status_but, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(appDesktop_Status_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        appDesktop_Status_PanelLayout.setVerticalGroup(
            appDesktop_Status_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appDesktop_Status_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appDesktop_Status_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(appDesktop_Status_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblCompanyName.setBackground(new java.awt.Color(255, 255, 255));
        lblCompanyName.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblCompanyName.setForeground(new java.awt.Color(0, 0, 102));
        lblCompanyName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompanyName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 153), 1, true));
        lblCompanyName.setOpaque(true);

        jDesktopPane.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(appDesktop_Status_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(lblCompanyName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                        .addComponent(lblCompanyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(appDesktop_Status_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(appDesktop_Status_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCompanyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Setting");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        jMenuItem4.setText("New Tables");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem4);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        /**
        jMenu1.setText("Send");
        */

        jMenuItem9.setText("Disbursed Loan ");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem6.setText("Outstanding");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Due");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem2.setText("Arrears");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem5.setText("Payment");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem3.setText("Receipt");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem12.setText("Jurnal");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem17.setText("Early Settlement");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem17);

        jMenuItem13.setText("Message To Member");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem13);

        jMenuItem16.setText("Message To Multicluster");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem16);

        menuBar.add(jMenu1);

        /**
        jMenu2.setText("Other");
        */

        jMenuItem1.setText("Custom Message");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem14.setText("Message to Member");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuItem15.setText("Message to Multicluster");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuItem8.setText("Message Monitor");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenu3.setText("Histry");

        jMenuItem10.setText("Receive Message");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Send Message");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenu2.add(jMenu3);

        jMenuItem18.setText("Message Counter");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem18);

        menuBar.add(jMenu2);

        jMenu4.setText("Automated");

        jMenuItem19.setText("Automate");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem19);

        menuBar.add(jMenu4);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void appDesktop_Status_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appDesktop_Status_butActionPerformed

        String butString = appDesktop_Status_but.getText().trim();

        if (butString.equalsIgnoreCase("CONNECT")) {
            startSMSServer();

        } else if (butString.equalsIgnoreCase("DISCONNECT")) {
            stopSMSServer();
        }


    }//GEN-LAST:event_appDesktop_Status_butActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed

        Runnable runble = new Runnable() {

            @Override
            public void run() {
                Setting inf = new Setting();
                ApplicationDesktop.jDesktopPane.add(inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();

    }//GEN-LAST:event_openMenuItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
//                Arrears_infrm_view inf = new Arrears_infrm_view ();
                LoanArrears_infrm_view_3 inf = new LoanArrears_infrm_view_3();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
                ReceiptJIFrame_view_2 inf = new ReceiptJIFrame_view_2();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
                NewTableCreation_view inf = new NewTableCreation_view();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
                Payment_infrm_view_2 inf = new Payment_infrm_view_2();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
//                Outstanding_infrm_view inf = new Outstanding_infrm_view ();
                LoanOutstanding_infrm_view inf = new LoanOutstanding_infrm_view();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
//                DueLoan_infrm_view inf = new DueLoan_infrm_view ();
                LoanDue_infrm_view inf = new LoanDue_infrm_view();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
//                DueLoan_infrm_view inf = new DueLoan_infrm_view ();
                CustomMessage_view inf = new CustomMessage_view();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem8ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem8ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
//                DueLoan_infrm_view inf = new DueLoan_infrm_view ();
                ReceiveAndSendMonitorView inf = new ReceiveAndSendMonitorView();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem10ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem10ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
//                DueLoan_infrm_view inf = new DueLoan_infrm_view ();
                HistryReceivedMessageView inf = new HistryReceivedMessageView();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem11ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem11ActionPerformed

        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
//                DueLoan_infrm_view inf = new DueLoan_infrm_view ();
                HistrySendMessageView inf = new HistrySendMessageView();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();

    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
                ReceiptJIFrame_view_2 inf = new ReceiptJIFrame_view_2();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
                Payment_infrm_view_2 inf = new Payment_infrm_view_2();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
//                Outstanding_infrm_view inf = new Outstanding_infrm_view ();
//                LoanOutstanding_infrm_view_2 inf = null;

                if (Company_Profile.getLanguage().trim().equalsIgnoreCase(Company_Profile.LanguageEnum.SINHALA.toString().trim())) {
                    LoanOutstanding_infrm_view_3 inf = new LoanOutstanding_infrm_view_3();
                    ApplicationDesktop.jDesktopPane.add(inf);
                    WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                    inf.setVisible(true);
                } else {
                    LoanOutstanding_infrm_view_2 inf = new LoanOutstanding_infrm_view_2();
                    ApplicationDesktop.jDesktopPane.add(inf);
                    WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                    inf.setVisible(true);
                }

            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
//                DueLoan_infrm_view inf = new DueLoan_infrm_view ();
                LoanDue_infrm_view_2 inf = new LoanDue_infrm_view_2();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
//                Arrears_infrm_view inf = new Arrears_infrm_view ();
                LoanArrears_infrm_view_3 inf = new LoanArrears_infrm_view_3();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton6ActionPerformed
    {//GEN-HEADEREND:event_jButton6ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
//                DueLoan_infrm_view inf = new DueLoan_infrm_view ();
                CustomMessage_view inf = new CustomMessage_view();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton9ActionPerformed
    {//GEN-HEADEREND:event_jButton9ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
                MessageToMemebers_view_in_Multicluster_2 inf = new MessageToMemebers_view_in_Multicluster_2();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton10ActionPerformed
    {//GEN-HEADEREND:event_jButton10ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
//                DueLoan_infrm_view inf = new DueLoan_infrm_view ();
                HistryReceivedMessageView inf = new HistryReceivedMessageView();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton11ActionPerformed
    {//GEN-HEADEREND:event_jButton11ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
//                DueLoan_infrm_view inf = new DueLoan_infrm_view ();
                HistrySendMessageView inf = new HistrySendMessageView();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem12ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem12ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
                Jurnal_if_view_2 inf = new Jurnal_if_view_2();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton7ActionPerformed
    {//GEN-HEADEREND:event_jButton7ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
                Jurnal_if_view_2 inf = new Jurnal_if_view_2();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem13ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem13ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
                MessageToMemebers_view inf = new MessageToMemebers_view();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton12ActionPerformed
    {//GEN-HEADEREND:event_jButton12ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
//                DueLoan_infrm_view inf = new DueLoan_infrm_view ();
                ReceiveAndSendMonitorView inf = new ReceiveAndSendMonitorView();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton13ActionPerformed
    {//GEN-HEADEREND:event_jButton13ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
                MessageToMemebers_view_2 inf = new MessageToMemebers_view_2();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem14ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem14ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
                MessageToMemebers_view_2 inf = new MessageToMemebers_view_2();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem15ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem15ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
                MessageToMemebers_view_in_Multicluster_2 inf = new MessageToMemebers_view_in_Multicluster_2();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem16ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem16ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
                MessageToMemebers_view_in_Multicluster_2 inf = new MessageToMemebers_view_in_Multicluster_2();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

          private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
              Runnable runble;
              runble = new Runnable() {

                  @Override
                  public void run() {
                      LoanDisbursed_infrm_view inf = new LoanDisbursed_infrm_view();
                      ApplicationDesktop.jDesktopPane.add(inf);
                      WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                      inf.setVisible(true);
                  }
              };

              new Thread(runble).start();
          }//GEN-LAST:event_jMenuItem9ActionPerformed

          private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
              Runnable runble;
              runble = new Runnable() {

                  @Override
                  public void run() {
                      LoanDisbursed_infrm_view inf = new LoanDisbursed_infrm_view();
                      ApplicationDesktop.jDesktopPane.add(inf);
                      WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                      inf.setVisible(true);
                  }
              };

              new Thread(runble).start();
          }//GEN-LAST:event_jButton8ActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        earlySettlementButtonAction();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        earlySettlementButtonAction();
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
//                DueLoan_infrm_view inf = new DueLoan_infrm_view ();
                MessageCounter_INF inf = new MessageCounter_INF();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
//                DueLoan_infrm_view inf = new DueLoan_infrm_view ();
                MessageCounter_INF inf = new MessageCounter_INF();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
//                DueLoan_infrm_view inf = new DueLoan_infrm_view ();
                AutomateUI inf = new AutomateUI();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
                     * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
                     * If Nimbus (introduced in Java SE 6) is not available,
                     * stay with the default look and feel. For details see
                     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
                     * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationDesktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    public static javax.swing.JPanel appDesktop_Status_Panel;
    public static javax.swing.JToggleButton appDesktop_Status_but;
    public static javax.swing.JLabel appDesktop_Status_lbl;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    public static javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    public static javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    // End of variables declaration//GEN-END:variables

    private void earlySettlementButtonAction() {
        Runnable runble;
        runble = new Runnable() {

            @Override
            public void run() {
                LoanEarlySettlement_infrm_view inf = new LoanEarlySettlement_infrm_view();
                ApplicationDesktop.jDesktopPane.add(inf);
                WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, inf);
                inf.setVisible(true);
            }
        };

        new Thread(runble).start();
    }

    private void startSMSServer() {

        Thread trdStartService = new Thread(new Runnable() {
            @Override
            public void run() {

//                mySMSServer = new MySMSServer ();
//                mySMSServer.startService ();
                new MySMSServer().assignGateway();

            }
        });
        trdStartService.start();

    }

    private void stopSMSServer() {

        new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    MySMSServer.smsServerService.stopService();
                } catch (SMSLibException ex) {
                    Logger.getLogger(ApplicationDesktop.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(ApplicationDesktop.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InterruptedException ex) {
                    Logger.getLogger(ApplicationDesktop.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();

//        try
//        {
//            MySMSServer.getSmsServerService ().getInstance ().stopService ();
//        } catch (SMSLibException ex)
//        {
//            Logger.getLogger (ApplicationDesktop.class.getName ()).log (Level.SEVERE, null, ex);
//        } catch (IOException ex)
//        {
//            Logger.getLogger (ApplicationDesktop.class.getName ()).log (Level.SEVERE, null, ex);
//        } catch (InterruptedException ex)
//        {
//            Logger.getLogger (ApplicationDesktop.class.getName ()).log (Level.SEVERE, null, ex);
//        }
    }

    public static void setStatus(String statusPara) {

        String status = statusPara;
        System.out.println("status>" + status);
        Service.ServiceStatus serviceStatus = MySMSServer.getSmsServerService().getServiceStatus();

        if (status.equalsIgnoreCase(Service.ServiceStatus.STARTING.toString())) {
//            appDesktop_Status_but.setText ("DISCONNECT");
            appDesktop_Status_lbl.setText("STARTING");
//            appDesktop_Status_Panel.setBackground (Color.GREEN.darker ());
        }

        if (status.equalsIgnoreCase(Service.ServiceStatus.STARTED.toString())) {
            appDesktop_Status_but.setText("DISCONNECT");
            appDesktop_Status_lbl.setText("STARTED");
            appDesktop_Status_Panel.setBackground(Color.GREEN.darker());
        }

        if (status.equalsIgnoreCase(Service.ServiceStatus.STOPPING.toString())) {
//            appDesktop_Status_but.setText ("CONNECT");
            appDesktop_Status_lbl.setText("STOPPING");
//            appDesktop_Status_Panel.setBackground (Color.RED.darker ());
        }

        if (status.equalsIgnoreCase(Service.ServiceStatus.STOPPED.toString())) {
            appDesktop_Status_but.setText("CONNECT");
            appDesktop_Status_lbl.setText("STOPPED");
            appDesktop_Status_Panel.setBackground(Color.RED.darker());
        }

    }

    public static void setStatusAsStart() {
        appDesktop_Status_but.setText("DISCONNECT");
        appDesktop_Status_lbl.setText("STARTED");
        appDesktop_Status_Panel.setBackground(Color.GREEN.darker());
    }

    public static void setStatusAsStop() {
        appDesktop_Status_but.setText("CONNECT");
        appDesktop_Status_lbl.setText("STOPPED");
        appDesktop_Status_Panel.setBackground(Color.RED.darker());
    }

//    private void loadDefaultSetting() {
//
//        SettingLoader.loadSetting();
//
////        if (!SettingLoader.loadSetting()) {
////            
////            
////            
////            setStatusAsStop();
//////            Home.setLblMessage("");
//////            Home.setLblMessage("Please check your system setting");
////            JOptionPane.showMessageDialog(rootPane, "Check Your Setting.", "Warning", JOptionPane.WARNING_MESSAGE);
////
////        } else {
////            setStatusAsStart();
//////            Home.setLblMessage("");
////
////        }
//    }
    private void onLoad() {
        String cmpName = Company_Profile.getCompanyName();
        lblCompanyName.setText("<HTML>" + cmpName + "</HTML>");
    }

}
