/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iroshan.com.smsserver.view;

import iroshan.com.common.utility.MyMessagesUtility;
import iroshan.com.common.utility.MyPhoneNoFormatingUtility;
import iroshan.com.common.utility.MyRounding;
import iroshan.com.common.utility.WindowLocation;
import iroshan.com.smsserver.pojo.Loan_pojo;
import iroshan.com.smsserver.enums.MessageStatusEnum;
import iroshan.com.smsserver.enums.MyMessageTypeEnum;
import iroshan.Company_Profile;
import iroshan.com.smsserver.service.Loan_service;
import iroshan.com.smsserver.service.MySMSServer;
import iroshan.com.smsserver.service.SMSCount_Service;
import iroshan.com.smsserver.service.SendMessage;
import java.awt.Rectangle;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.smslib.OutboundMessage;

/**
 *
 * @author Iroshan
 */
public class LoanOutstanding_infrm_view_2 extends javax.swing.JInternalFrame {

    ShowMessageDetails_INF showMessageDetails_INF = new ShowMessageDetails_INF();

    SendMessage sendMessage = null;
    Thread trdSend = null;
    Loan_service loan_service = null;

    int currentRow = 0;
    int findCurrentRow = 0;
    int preveiesEvent = -1; // 1= down 2=up

//  WAITING DIALOG - START ***************************************
    WaitingDialogSMSSend waitingDialogSMSSend;
    Thread trdWaiting;
// WAITING DIALOG - END ******************************************

    /**
     * Creates new form CustomerUploder
     */
    private static LoanOutstanding_infrm_view_2 arrears_infrm_view = null;
//    Map<Integer, Loan_pojo> outstandingMap = null;
//    List<Arrears_pojo> arearsList = null;

//    static Map<Integer, Loan_pojo> loanOutstandingMap;
    static List<Loan_pojo> loanOutstandingList;

    public LoanOutstanding_infrm_view_2() {
        initComponents();
        arrears_infrm_view = this;
        WindowLocation.setJinternalFrameToCenter(ApplicationDesktop.jDesktopPane, this);
        loadProduct();
        loadCenter();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPending = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        dateTF = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        tfCustomer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbProduct = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbCenter = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("OUTSTANDING 2");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/iroshan/com/smsserver/view/Messaging.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblPending.setAutoCreateRowSorter(true);
        tblPending.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SELECT", "#", "CODE", "NAME", "ACCOUNT OFFICE NO", "PHONE", "MESSAGE", "A/C", "GRANTED DATE", "GRANTED AMOUNT", "CAPITAL", "INTEREST", "OUTSTANDING CAPITAL", "OUTSTANDING INTEREST", "TOTAL OUTSTANDING AMOUNT", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPending.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblPending.setFillsViewportHeight(true);
        tblPending.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblPendingMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblPending);

        jButton1.setText("SELECT ALL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setText("UNSELECT ALL");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton4.setText("Show Message");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton6)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
        );

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("CLOSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("SEND");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jButton2.setText("LOAD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Date :");

        dateTF.setBackground(new java.awt.Color(255, 255, 255));
        dateTF.setDate(new Date());
        dateTF.setDateFormatString("yyyy-MM-dd");

        jLabel1.setText("Customer :");

        jLabel2.setText("Product :");

        cmbProduct.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));

        jLabel4.setText("Center :");

        cmbCenter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateTF, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(tfCustomer))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(8, 8, 8)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbProduct, 0, 251, Short.MAX_VALUE)
                    .addComponent(cmbCenter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(tfCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbCenter)
                        .addComponent(jButton2))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Loan Outstanding");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        loadFieldOfficerTransactionTBL();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        sendSms_2();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblPendingMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tblPendingMouseReleased
    {//GEN-HEADEREND:event_tblPendingMouseReleased
//        tblSelectProsesing ();        
    }//GEN-LAST:event_tblPendingMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        selectAllProcessing();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton6ActionPerformed
    {//GEN-HEADEREND:event_jButton6ActionPerformed
        unselectAllProcessing();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        showMessageInf();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        closeMessageInf();
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbCenter;
    private javax.swing.JComboBox cmbProduct;
    private com.toedter.calendar.JDateChooser dateTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPending;
    private javax.swing.JTextField tfCustomer;
    // End of variables declaration//GEN-END:variables

    public static LoanOutstanding_infrm_view_2 getArrears_infrm_view() {
        return arrears_infrm_view;
    }

    public static void setArrears_infrm_view(LoanOutstanding_infrm_view_2 arrears_infrm_view) {
        LoanOutstanding_infrm_view_2.arrears_infrm_view = arrears_infrm_view;
    }

//    public static Map<Integer, Loan_pojo> getLoanOutstandingMap ()
//    {
//        return loanOutstandingMap;
//    }
//
//    public static void setLoanOutstandingMap (Map<Integer, Loan_pojo> loanOutstandingMap)
//    {
//        LoanOutstanding_infrm_view.loanOutstandingMap = loanOutstandingMap;
//    }
    public static List<Loan_pojo> getLoanOutstandingList() {
        return loanOutstandingList;
    }

    public static void setLoanOutstandingList(List<Loan_pojo> loanOutstandingList) {
        LoanOutstanding_infrm_view_2.loanOutstandingList = loanOutstandingList;
    }

    private void loadFieldOfficerTransactionTBL() {

        Runnable runBle = new Runnable() {

            @Override
            public void run() {

                DefaultTableModel dfTblMd = (DefaultTableModel) tblPending.getModel();
                int sizeTbl = dfTblMd.getRowCount();
                for (int i = 0; i < sizeTbl; i++) {
                    dfTblMd.removeRow(0);
                }

                String productCodeAndName = "-1";
                if (cmbProduct.getSelectedIndex() == 0) {
                    productCodeAndName = "-1";
                } else {

                    productCodeAndName = cmbProduct.getSelectedItem().toString().trim();
                    String[] productCodeAndNameArr = productCodeAndName.split("-");
                    productCodeAndName = productCodeAndNameArr[0].trim();

                }

                String centerCodeAndName = "-1";
                if (cmbCenter.getSelectedIndex() == 0) {
                    centerCodeAndName = "-1";
                } else {
                    centerCodeAndName = cmbCenter.getSelectedItem().toString().trim();
                    String[] centerCodeAndNameArr = centerCodeAndName.split("-");
                    centerCodeAndName = centerCodeAndNameArr[0].trim();

                }

                String customer = tfCustomer.getText();
                if (customer.isEmpty()) {
                    customer = "-1";
                } else {
                    customer = customer.trim();
                }

                Date dateSelected = dateTF.getDate();
                if (dateSelected == null) {
                    MyMessagesUtility.showWarning("Set the Date");
                } else {
                    if (Company_Profile.getLanguage().trim().equalsIgnoreCase(Company_Profile.LanguageEnum.SINHALA.toString().trim())) {
                        loanOutstandingList = new Loan_service().getLoanOutstandingDetails(dateSelected, productCodeAndName, centerCodeAndName, customer);
                        loadArrearsToTables();
                    } else {
                        loanOutstandingList = new Loan_service().getLoanOutstandingDetails(dateSelected, productCodeAndName, centerCodeAndName, customer);
                        loadArrearsToTables();
                    }

                }

            }
        };
        new Thread(runBle).start();

    }

    public void loadArrearsToTables() {

        Date dateSelected = dateTF.getDate();

//        PENDING
        DefaultTableModel dfTblMdPending = (DefaultTableModel) tblPending.getModel();
        int rowCountPending = dfTblMdPending.getRowCount();

        for (int i = 0; i < rowCountPending; i++) {
            dfTblMdPending.removeRow(0);
        }

//        SENT
//        DefaultTableModel dfTblMdSent = (DefaultTableModel) tblSent.getModel ();
//        int rowCountSent = dfTblMdSent.getRowCount ();
//
//        for (int i = 0 ; i < rowCountSent ; i++)
//        {
//            dfTblMdSent.removeRow (0);
//        }
//        UNSENT
//        DefaultTableModel dfTblMdUnsent = (DefaultTableModel) tblUnsent.getModel ();
//        int rowCountUnsent = dfTblMdUnsent.getRowCount ();
//
//        for (int i = 0 ; i < rowCountUnsent ; i++)
//        {
//            dfTblMdUnsent.removeRow (0);
//        }
        int pendingSeqId = 0;
        int sentSeqId = 0;
        int unsentSeqId = 0;

//        Map<Integer, Loan_pojo> outstandingMap = loanOutstandingMap;
        List<Loan_pojo> outstandingMap = loanOutstandingList;

//        for (Map.Entry<Integer, Loan_pojo> entrySet : outstandingMap.entrySet ())
//        {
        for (int i = 0; i < outstandingMap.size(); i++) {

//            Integer key = entrySet.getKey ();
//            Loan_pojo value = entrySet.getValue ();
            Loan_pojo value = outstandingMap.get(i);

            Boolean isSelected = value.getIsSelected();
            String cusCode = value.getCusCode();
            String cusName = value.getCusName();
            String cusOfficeNo = value.getCusOfficeNo();

            String acNumber = value.getAcNumber();
            String phoneNo = value.getTelephoneNo().trim();
            String message = value.getMessage().trim();
            Date disburseDate = value.getDisburseDate();

            String loanAmount = ((value.getDisburseAmount() == null) ? "0.00" : MyRounding.roundToLastTwoDecimal(value.getDisburseAmount()));

            String capitalAmount = ((value.getCapitalFullLoan() == null) ? "0.00" : MyRounding.roundToLastTwoDecimal(value.getCapitalFullLoan()));
            String interestAmount = ((value.getInterestFullLoan() == null) ? "0.00" : MyRounding.roundToLastTwoDecimal(value.getInterestFullLoan()));
            String outstandingCapital = ((value.getOutstandingCapital() == null) ? "0.00" : MyRounding.roundToLastTwoDecimal(value.getOutstandingCapital()));
            String outstandingInterest = ((value.getOutstandingInterest() == null) ? "0.00" : MyRounding.roundToLastTwoDecimal(value.getOutstandingInterest()));
            String totalOutstanding = ((value.getTotalOutstanding() == null) ? "0.00" : MyRounding.roundToLastTwoDecimal(value.getTotalOutstanding()));

            String dueCapital = ((value.getDueCapital() == null) ? "0.00" : MyRounding.roundToLastTwoDecimal(value.getDueCapital()));
            String dueInterest = ((value.getDueInterest() == null) ? "0.00" : MyRounding.roundToLastTwoDecimal(value.getDueInterest()));
            String totalDue = ((value.getTotalDue() == null) ? "0.00" : MyRounding.roundToLastTwoDecimal(value.getTotalDue()));

            String arearsCapital = ((value.getArearsCapital() == null) ? "0.00" : MyRounding.roundToLastTwoDecimal(value.getArearsCapital()));
            String arearsInterst = ((value.getArearsInterst() == null) ? "0.00" : MyRounding.roundToLastTwoDecimal(value.getArearsInterst()));
            String totalArears = ((value.getTotalArears() == null) ? "0.00" : MyRounding.roundToLastTwoDecimal(value.getTotalArears()));
            String msgStatus = value.getMsgStatus();

            if (msgStatus.equalsIgnoreCase(MessageStatusEnum.PENDING.toString())) {

                ++pendingSeqId;
// "SELECT", "#", "CUSTOMER CODE", "PHONE", "MESSAGE", "A/C", "GRANTED DATE", "GRANTED AMOUNT", "ARREARS CAPITAL", "ARREARS INTEREST", "TOTAL ARREARS AMOUNT", "STATUS"
                dfTblMdPending.addRow(new Object[]{
                    isSelected, pendingSeqId, cusCode, cusName, cusOfficeNo, phoneNo, message, acNumber, disburseDate, loanAmount, capitalAmount,
                    interestAmount, outstandingCapital, outstandingInterest, totalOutstanding, msgStatus
                });

            }

//            else if (msgStatus.equalsIgnoreCase (MessageStatusEnum.SENT.toString ()))
//            {
//
//                ++sentSeqId;
////"#", "CODE", "PHONE", "MESSAGE", "STATUS", "MFO", "A/C", "DUE AMOUNT", "TO DATE", "TOTAL ARREARS CAPITAL", "TOTAL ARREARS INTEREST", "TOTAL ARREARS AMOUNT", "GRANTED AMOUNT", "GRANTED DATE", "GRANTED DETAILS"
//                dfTblMdSent.addRow (new Object[]
//                {
//                    sentSeqId, cusCode, cusName, cusOfficeNo, phoneNo, message, acNumber, disburseDate, loanAmount, capitalAmount,
//                    interestAmount, outstandingCapital, outstandingInterest, totalOutstanding, msgStatus
//                });
//
//            } else if (msgStatus.equalsIgnoreCase (MessageStatusEnum.UNSENT.toString ()))
//            {
//
//                ++unsentSeqId;
////"#", "CODE", "PHONE", "MESSAGE", "STATUS", "MFO", "A/C", "DUE AMOUNT", "TO DATE", "TOTAL ARREARS CAPITAL", "TOTAL ARREARS INTEREST", "TOTAL ARREARS AMOUNT", "GRANTED AMOUNT", "GRANTED DATE", "GRANTED DETAILS"
//                dfTblMdUnsent.addRow (new Object[]
//                {
//                    isSelected, unsentSeqId, cusCode, cusName, cusOfficeNo, phoneNo, message, acNumber, disburseDate, loanAmount, capitalAmount,
//                    interestAmount, outstandingCapital, outstandingInterest, totalOutstanding, msgStatus
//                });
//
//            } else if (msgStatus.equalsIgnoreCase (MessageStatusEnum.FAILED.toString ()))
//            {
//
//                ++unsentSeqId;
////"#", "CODE", "PHONE", "MESSAGE", "STATUS", "MFO", "A/C", "DUE AMOUNT", "TO DATE", "TOTAL ARREARS CAPITAL", "TOTAL ARREARS INTEREST", "TOTAL ARREARS AMOUNT", "GRANTED AMOUNT", "GRANTED DATE", "GRANTED DETAILS"
//                dfTblMdUnsent.addRow (new Object[]
//                {
//                    isSelected, unsentSeqId, cusCode, cusName, cusOfficeNo, phoneNo, message, acNumber, disburseDate, loanAmount, capitalAmount,
//                    interestAmount, outstandingCapital, outstandingInterest, totalOutstanding, msgStatus
//                });
//
//            }
        }

        tblPending.revalidate();
    }

    public void loadArrearsToTables(String recipientPara, String textPara, String messageStatusStringPara) {

        String recipient = recipientPara.trim();
        String text = textPara.trim();
        String messageStatusString = messageStatusStringPara;

        List<Loan_pojo> outstandingList = loanOutstandingList;
        if (outstandingList != null) {

            for (int i = 0; i < outstandingList.size(); i++) {
                Loan_pojo loanPojo = outstandingList.get(i);

                String telList = loanPojo.getTelephoneNo().trim();
                String msgList = loanPojo.getMessage().trim();

                recipient = MyPhoneNoFormatingUtility.formatToPlus94Number(recipient);
                telList = MyPhoneNoFormatingUtility.formatToPlus94Number(telList);

                if (recipient.equalsIgnoreCase(telList) && text.equalsIgnoreCase(msgList)) {
                    outstandingList.remove(i);
                    loanPojo.setMsgStatus(messageStatusString);
                    outstandingList.add(loanPojo);
//                    new SendMessageSaveDao ().saveToDB (MyMessageTypeEnum.OUTSTANDING.toString (), -1, telList, msgList, om.getDate ());
                }

            }

        }

        loadArrearsToTables();

    }

    private void sendSms_2() {

        trdSend = new Thread(new Runnable() {
            @Override
            public void run() {

                int sentSMSCount = 0;
                int sentConfirmSMSCount = 0;

                if (MyMessagesUtility.showConfirmDoYouWantToRemove("Confirm ?") == 0) {

                    try {
                        //-------------------------------------------------------
                        trdWaiting = new Thread(new Runnable() {
                            @Override
                            public void run() {
                                waitingDialogSMSSend = new WaitingDialogSMSSend("", "Starting ...", ApplicationDesktop.appDesktop, true);
                                waitingDialogSMSSend.setVisible(true);
                            }
                        });
                        trdWaiting.start();
                        //-------------------------------------------------------

                        if (loan_service == null) {
                            loan_service = new Loan_service();
                        }
                        if (sendMessage == null) {
                            sendMessage = new SendMessage();
                        }

                        // --------------------------------------------------
                        Company_Profile.setMsgSendStart(true);
                        // --------------------------------------------------

                        DefaultTableModel dfTblMd = (DefaultTableModel) tblPending.getModel();
                        int rowCount = dfTblMd.getRowCount();

                        //-------------------------------------
                        MySMSServer.restartService();
                        //-------------------------------------

                        String messageType = MyMessageTypeEnum.OUTSTANDING.toString().trim();

                        OutboundMessage.MessageStatuses confirmStart = sendMessage.sendConfirm_1(Company_Profile.getConfirmTeleNo(), messageType + " sending start..");
                        if (!confirmStart.toString().trim().equals(MessageStatusEnum.SENT.toString().trim())) {
                            MyMessagesUtility.showWarning(messageType + " " + confirmStart.toString());
                        } else if (confirmStart.toString().trim().equals(MessageStatusEnum.SENT.toString().trim())) {
                            ++sentConfirmSMSCount;
                        }

                        outerLoop:
                        for (int i = currentRow; i < rowCount; i++) {

                            if (!Company_Profile.getMsgSendStart()) // IF MSG SENDING STOPED
                            {
                                break outerLoop;
                            }

                            int j = i;
                            ++j;

                            try {
                                Thread.sleep(500);
                            } catch (InterruptedException ex) {
                                Logger.getLogger(Jurnal_if_view_2.class.getName()).log(Level.SEVERE, null, ex);
                            }

                            //----------------------------------------
                            String customeMessage = "On Processing : " + j + "/" + rowCount;
                            waitingDialogSMSSend.setCustomMessage(customeMessage);

                            tblPending.setRowSelectionInterval(i, i);
                            tblPending.scrollRectToVisible(new Rectangle(tblPending.getCellRect(i, 0, true)));
                            //----------------------------------------

                            Boolean isSelected = Boolean.valueOf(String.valueOf(dfTblMd.getValueAt(i, 0)));
                            if (isSelected) {
                                if (!dfTblMd.getValueAt(i, 15).toString().trim().equalsIgnoreCase(OutboundMessage.MessageStatuses.SENT.toString())) {
//                                String voucherNo = String.valueOf (dfTblMd.getValueAt (i, 2));
//                                String cusCode = String.valueOf (dfTblMd.getValueAt (i, 3));

                                    String phoneNo = String.valueOf(dfTblMd.getValueAt(i, 5));
                                    String message = String.valueOf(dfTblMd.getValueAt(i, 6));

// SEND
                                    OutboundMessage.MessageStatuses msgStatus = loan_service.sendSMS_2(messageType, phoneNo, message);
                                    if (msgStatus.toString().trim().equalsIgnoreCase(OutboundMessage.MessageStatuses.SENT.toString().trim())) {
                                        ++sentSMSCount;
                                    }
                                    dfTblMd.setValueAt(msgStatus.toString(), i, 15);
                                }

                            }
                            currentRow = i;
                        }

                        waitingDialogSMSSend.dispose();
                        trdWaiting.interrupt();

                        OutboundMessage.MessageStatuses confirmEnd = sendMessage.sendConfirm_1(Company_Profile.getConfirmTeleNo(), messageType + " sending end with " + sentSMSCount + " messages.");
                        if (!confirmEnd.toString().trim().equals(MessageStatusEnum.SENT.toString().trim())) {
                            MyMessagesUtility.showWarning(messageType + " " + confirmEnd.toString());
                        } else if (confirmEnd.toString().trim().equals(MessageStatusEnum.SENT.toString().trim())) {
                            ++sentConfirmSMSCount;
                        }

                        new SMSCount_Service().saveSMSCount(messageType, sentSMSCount);
                        new SMSCount_Service().saveSMSCount(MyMessageTypeEnum.CONFIRM.toString().trim(), sentConfirmSMSCount);
                    } catch (Exception ex) {
                        MyMessagesUtility.showError(ex.toString());
                        Logger.getLogger(LoanOutstanding_infrm_view_2.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
        trdSend.start();

    }

    private void sendSms() {

        new Thread(new Runnable() {

            @Override
            public void run() {

                if (MyMessagesUtility.showConfirmDoYouWantToRemove("Confirm ?") == 0) {
//                    --------------------------------------
                    Company_Profile.setMsgSendStart(true);
//                    --------------------------------------

                    List<Loan_pojo> loanArearsMap2 = new ArrayList<Loan_pojo>();

                    DefaultTableModel dfTblMd = (DefaultTableModel) tblPending.getModel();
                    int rowCount = dfTblMd.getRowCount();

                    for (int i = 0; i < rowCount; i++) {
                        Boolean isSelected2 = Boolean.valueOf(dfTblMd.getValueAt(i, 0).toString());

                        String phoneNo = dfTblMd.getValueAt(i, 5).toString();
                        String message = dfTblMd.getValueAt(i, 6).toString();

                        Loan_pojo loanPojo = new Loan_pojo();
                        loanPojo.setIsSelected(isSelected2);
                        loanPojo.setTelephoneNo(phoneNo);
                        loanPojo.setMessage(message);

                        loanArearsMap2.add(loanPojo);

//                        tblSelectProsesing (i);
                    }

                    if (loanArearsMap2.size() > 0) {
                        new Loan_service().sendOutstandingSms(loanArearsMap2);
                    }

                }

            }
        }).start();

    }

    private void tblSelectProsesing() {

        DefaultTableModel dfTblMd = (DefaultTableModel) tblPending.getModel();
        int rowCount = dfTblMd.getRowCount();
        for (int j = 0; j < rowCount; j++) {
            Boolean isSelectedBoo = Boolean.getBoolean(dfTblMd.getValueAt(j, 0).toString().trim());
            String cusCode = dfTblMd.getValueAt(j, 2).toString().trim();
            String ac = dfTblMd.getValueAt(j, 5).toString().trim();

            List<Loan_pojo> loanArearsMap = getLoanOutstandingList();
            for (int i = 0; i < loanArearsMap.size(); i++) {
                Loan_pojo loanPojo = loanArearsMap.get(i);

                String listCusCode = loanPojo.getCusCode().trim();
                String listAC = loanPojo.getAcNumber().trim();

                if (listCusCode.equalsIgnoreCase(cusCode) && listAC.equalsIgnoreCase(ac)) {
                    loanArearsMap.remove(loanPojo);
                }
                if (isSelectedBoo == true) {
                    loanPojo.setIsSelected(false);
                }
                if (isSelectedBoo == false) {
                    loanPojo.setIsSelected(false);
                }

                loanArearsMap.add(loanPojo);

            }
        }

    }

    private void selectAllProcessing() {
        List<Loan_pojo> loanArearsMap = getLoanOutstandingList();
        int size = loanArearsMap.size();
        for (int i = 0; i < size; i++) {
            Loan_pojo loanPojo = loanArearsMap.get(i);

            loanArearsMap.remove(loanPojo);

            loanPojo.setIsSelected(true);
            loanArearsMap.add(i, loanPojo);

        }

        loadArrearsToTables();
    }

    private void unselectAllProcessing() {
        List<Loan_pojo> loanArearsMap = getLoanOutstandingList();
        int size = loanArearsMap.size();
        for (int i = 0; i < size; i++) {
            Loan_pojo loanPojo = loanArearsMap.get(i);

            loanArearsMap.remove(loanPojo);

            loanPojo.setIsSelected(false);
            loanArearsMap.add(i, loanPojo);

        }

        loadArrearsToTables();
    }

    private void loadProduct() {
        cmbProduct.removeAllItems();
        cmbProduct.addItem("Select");

        List<String> list = new Loan_service().loadProduct();
        for (String listObj : list) {
            cmbProduct.addItem(listObj);
        }
    }

    private void loadCenter() {
        cmbCenter.removeAllItems();
        cmbCenter.addItem("Select");

        List<String> list = new Loan_service().loadCenter();
        for (String listObj : list) {
            cmbCenter.addItem(listObj);
        }
    }

//    private void reSend ()
//    {
//        new Thread (new Runnable ()
//        {
//            @Override
//            public void run ()
//            {
//
//
//
//                if (MyMessagesUtility.showConfirmDoYouWantToRemove ("Confirm ?") == 0)
//                {
//
////                    --------------------------------------
//                    Company_Profile.setMsgSendStart (true);
////                    --------------------------------------
//                    List<Loan_pojo> loanArearsMap2 = new ArrayList<Loan_pojo> ();
//
//                    DefaultTableModel dfTblMd = (DefaultTableModel) tblUnsent.getModel ();
//                    int rowCount = dfTblMd.getRowCount ();
//
//
//
//                    for (int i = 0 ; i < rowCount ; i++)
//                    {
//                        Boolean isSelected2 = Boolean.valueOf (dfTblMd.getValueAt (i, 0).toString ());
//                        String phoneNo = dfTblMd.getValueAt (i, 5).toString ();
//                        String message = dfTblMd.getValueAt (i, 6).toString ();
//
//                        Loan_pojo loanPojo = new Loan_pojo ();
//                        loanPojo.setIsSelected (isSelected2);
//                        loanPojo.setTelephoneNo (phoneNo);
//                        loanPojo.setMessage (message);
//
//                        loanArearsMap2.add (loanPojo);
//
//                    }
//
//                    if (loanArearsMap2.size () > 0)
//                    {
//                        new Loan_service ().sendOutstandingSms (loanArearsMap2);
//                    }
//
//                }
//
//
//
//            }
//        }).start ();
//    }
//    private void tblUnsentSelectionProsesing ()
//    {
//
//        DefaultTableModel dfTblMd = (DefaultTableModel) tblUnsent.getModel ();
//        int rowCount = dfTblMd.getRowCount ();
//        for (int j = 0 ; j < rowCount ; j++)
//        {
//            Boolean isSelectedBoo = Boolean.getBoolean (dfTblMd.getValueAt (j, 0).toString ().trim ());
//            String cusCode = dfTblMd.getValueAt (j, 2).toString ().trim ();
//            String ac = dfTblMd.getValueAt (j, 5).toString ().trim ();
//
//
//            List<Loan_pojo> loanArearsMap = getLoanOutstandingList ();
//            for (int i = 0 ; i < loanArearsMap.size () ; i++)
//            {
//                Loan_pojo loanPojo = loanArearsMap.get (i);
//
//                String listCusCode = loanPojo.getCusCode ().trim ();
//                String listAC = loanPojo.getAcNumber ().trim ();
//
//                if (listCusCode.equalsIgnoreCase (cusCode) && listAC.equalsIgnoreCase (ac))
//                {
//                    loanArearsMap.remove (loanPojo);
//                }
//                if (isSelectedBoo == true)
//                {
//                    loanPojo.setIsSelected (false);
//                }
//                if (isSelectedBoo == false)
//                {
//                    loanPojo.setIsSelected (false);
//                }
//
//                loanArearsMap.add (loanPojo);
//
//            }
//        }
//    }
    private void showMessageInf() {

        int selectedRow = tblPending.getSelectedRow();
        String phnNo = tblPending.getValueAt(selectedRow, 5).toString().trim();
        String msg = tblPending.getValueAt(selectedRow, 6).toString().trim();
        String msgStutas = tblPending.getValueAt(selectedRow, 15).toString().trim();

        showMessageDetails_INF.showMessage(phnNo, msg, msgStutas);

    }

    public void closeMessageInf() {
        if (showMessageDetails_INF != null) {
            showMessageDetails_INF.dispose();
        }
    }

}
