/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iroshan.com.smsserver.view;

import iroshan.com.common.utility.MyDateAndTimeUtil;
import iroshan.com.common.utility.MyMessagesUtility;
import iroshan.com.smsserver.enums.MessageStatusEnum;
import iroshan.Company_Profile;
import iroshan.com.smsserver.enums.MyMessageTypeEnum;
import iroshan.com.smsserver.pojo.MessageToMemeberSearch_pojo;
import iroshan.com.smsserver.service.Cluster_service;
import iroshan.com.smsserver.service.MessageToMemebers_service;
import iroshan.com.smsserver.service.MySMSServer;
import iroshan.com.smsserver.service.SMSCount_Service;
import iroshan.com.smsserver.service.SendMessage;
import java.awt.Rectangle;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.smslib.OutboundMessage;

/**
 *
 * @author Iroshan
 */
public class MessageToMemebers_view_in_Multicluster_2 extends javax.swing.JInternalFrame {

    ShowMessageDetails_INF showMessageDetails_INF = new ShowMessageDetails_INF();

    SendMessage sendMessage = null;
    private static MessageToMemebers_view_in_Multicluster_2 messageToMemebers_view;
    static Map<Integer, MessageToMemeberSearch_pojo> tableMap;

    Thread trdSend = null;
    MessageToMemebers_service messageToMemebers_service = null;

    int currentRow = 0;
    int findCurrentRow = 0;
    int preveiesEvent = -1; // 1= down 2=up

//  WAITING DIALOG - START ***************************************
    WaitingDialogSMSSend waitingDialogSMSSend;
    Thread trdWaiting;
// WAITING DIALOG - END ******************************************

    public static MessageToMemebers_view_in_Multicluster_2 getMessageToMemebers_view() {
        return messageToMemebers_view;
    }

    public static void setMessageToMemebers_view(MessageToMemebers_view_in_Multicluster_2 aMessageToMemebers_view) {
        messageToMemebers_view = aMessageToMemebers_view;
    }

    /**
     * Creates new form MessageToMemebers
     */
    public MessageToMemebers_view_in_Multicluster_2() {
        initComponents();
        messageToMemebers_view = this;
        loadCenter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfMessage = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbCenter = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfTele = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfSubAcOfficeNo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmbSortBy = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        dfBirthday = new com.toedter.calendar.JDateChooser();
        tf_code_prefix = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPending = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Message to Memeber in Multicluster 2");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/iroshan/com/smsserver/img/Messaging.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel5.setText("Message :");

        tfMessage.setColumns(20);
        tfMessage.setRows(5);
        jScrollPane1.setViewportView(tfMessage);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Center :");

        cmbCenter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        jLabel2.setText("Name :");

        jLabel3.setText("Tele. :");

        jLabel4.setText("Sub A/C Office Code :");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Celar");

        jLabel6.setText("Sort by :");

        cmbSortBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEFAULT", "CODE", "NAME", "SUB A/C OFFICE NO", "TELE.", "BIRTHDAY", " " }));

        jLabel7.setText("Day for Birthday :");

        dfBirthday.setDateFormatString("yyyy-MM-dd");

        jLabel8.setText("Code Prefix :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(70, 70, 70)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2))
                                    .addComponent(tfTele)
                                    .addComponent(tfName)
                                    .addComponent(cmbCenter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_code_prefix, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dfBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbSortBy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(tfSubAcOfficeNo)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_code_prefix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfSubAcOfficeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(dfBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("SEND");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Select All");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton8.setText("Unselect All");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        tblPending.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SELECT", "#", "CODE", "NAME", "SUB A/C OFFICE NO", "TELE.", "BIRTHDAY", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPending.setFillsViewportHeight(true);
        tblPending.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblPending);

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setText("CLOSE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("CLEAR TABLE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton5.setText("Show Message");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton8)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        search();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed

        sendSms_2();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        selectAllProcessing();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton8ActionPerformed
    {//GEN-HEADEREND:event_jButton8ActionPerformed
        unselectAllProcessing();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton9ActionPerformed
    {//GEN-HEADEREND:event_jButton9ActionPerformed
        close();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton7ActionPerformed
    {//GEN-HEADEREND:event_jButton7ActionPerformed
        clearPendingTbl();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        showMessageInf();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        closeMessageInf();
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCenter;
    private javax.swing.JComboBox<String> cmbSortBy;
    private com.toedter.calendar.JDateChooser dfBirthday;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPending;
    private javax.swing.JTextArea tfMessage;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfSubAcOfficeNo;
    private javax.swing.JTextField tfTele;
    private javax.swing.JTextField tf_code_prefix;
    // End of variables declaration//GEN-END:variables

    private void loadCenter() {
        cmbCenter.removeAllItems();
        cmbCenter.addItem("Select");
        cmbCenter.addItem("ALL");

        List<String> list = new Cluster_service().getClusterAsString();
        for (String listObj : list) {
            cmbCenter.addItem(listObj);
        }
    }

    private void search() {
        Boolean aFlag = true;

        String center = null;
        String name;
        String tele;
        String subACOfficeNo;
        Date birthday;
        String sortBy;

        String code_prefix;
        code_prefix = tf_code_prefix.getText().trim();
        if (code_prefix.isEmpty()) {
            code_prefix = "";
        } else {
            code_prefix = code_prefix.trim();
        }

        if (cmbCenter.getSelectedIndex() == 0) {
            aFlag = false;
            MyMessagesUtility.showWarning("Select the center.");
        } else {
            center = cmbCenter.getSelectedItem().toString().trim();
            String centerArr[] = center.split("-");
            center = centerArr[0].trim();
        }

        name = tfName.getText().trim();
        if (name.isEmpty()) {
            name = "ALL";
        }

        tele = tfTele.getText().trim();
        if (tele.isEmpty()) {
            tele = "ALL";
        }

        subACOfficeNo = tfSubAcOfficeNo.getText().trim();
        if (subACOfficeNo.isEmpty()) {
            subACOfficeNo = "ALL";
        }

        birthday = dfBirthday.getDate();
        if (birthday == null) {
            birthday = null;
        }

        if (cmbSortBy.getSelectedIndex() == 0) {
            sortBy = "ALL";
        } else {
            sortBy = cmbSortBy.getSelectedItem().toString().trim();
        }

        if (aFlag) {
            tableMap = new MessageToMemebers_service().search(center, name, tele, subACOfficeNo, birthday, sortBy, code_prefix);
            loadTables();
        }

    }

    private void selectAllProcessing() {
        int rowNo = tblPending.getSelectedRow();
        DefaultTableModel dfTblMd = (DefaultTableModel) tblPending.getModel();
        int rowCount = dfTblMd.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            Boolean isSelected = Boolean.valueOf(dfTblMd.getValueAt(i, 0).toString().trim());
            Integer keyNo = Integer.valueOf(dfTblMd.getValueAt(i, 1).toString().trim());
//            String tel = dfTblMd.getValueAt (i, 2).toString ().trim ();
//            String msg = dfTblMd.getValueAt (i, 3).toString ().trim ();

            MessageToMemeberSearch_pojo messageToMemeberSearch_pojo = tableMap.get(keyNo);
            messageToMemeberSearch_pojo.setIsSelect(true);
            tableMap.remove(keyNo);
            tableMap.put(keyNo, messageToMemeberSearch_pojo);
        }

        loadTables();
    }

    private void unselectAllProcessing() {

//        int rowNo = tblPending.getSelectedRow ();
        DefaultTableModel dfTblMd = (DefaultTableModel) tblPending.getModel();
        int rowCount = dfTblMd.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            Boolean isSelected = Boolean.valueOf(dfTblMd.getValueAt(i, 0).toString().trim());
            Integer keyNo = Integer.valueOf(dfTblMd.getValueAt(i, 1).toString().trim());
//            String tel = dfTblMd.getValueAt (i, 2).toString ().trim ();
//            String msg = dfTblMd.getValueAt (i, 3).toString ().trim ();

            MessageToMemeberSearch_pojo messageToMemeberSearch_pojo = tableMap.get(keyNo);
            messageToMemeberSearch_pojo.setIsSelect(false);
            tableMap.remove(keyNo);
            tableMap.put(keyNo, messageToMemeberSearch_pojo);
        }

        loadTables();
    }

    public void loadTables() {

//        PENDING
        final DefaultTableModel dfTblMdPending = (DefaultTableModel) tblPending.getModel();
//        int rowCountPending = dfTblMdPending.getRowCount ();
//        for (int i = 0 ; i < rowCountPending ; i++)
//        {
//            dfTblMdPending.removeRow (0);
//        }
//        dfTblMdPending.setRowCount (0);

//        SENT
//        final DefaultTableModel dfTblMdSent = (DefaultTableModel) tblSent.getModel ();
//        int rowCountSent = dfTblMdSent.getRowCount ();
//
//        for (int j = 0 ; j < rowCountSent ; j++)
//        {
//            dfTblMdSent.removeRow (0);
//        }
//dfTblMdSent.setRowCount (0);
//        UNSENT
//        final DefaultTableModel dfTblMdUnsent = (DefaultTableModel) tblUnsent.getModel ();
//        int rowCountUnsent = dfTblMdUnsent.getRowCount ();
//
//        for (int k = 0 ; k < rowCountUnsent ; k++)
//        {
//            dfTblMdUnsent.removeRow (0);
//        }
//        dfTblMdUnsent.setRowCount (0);
        for (Map.Entry<Integer, MessageToMemeberSearch_pojo> entrySet : tableMap.entrySet()) {
            Integer keyNo = entrySet.getKey();
            MessageToMemeberSearch_pojo value = entrySet.getValue();

            Boolean isSelect = value.getIsSelect();

            String code = value.getCode();
            String name = value.getName();
            String acOfficeNo = value.getSubACOfficeNo();
            String memTeleNo = value.getTele();
            Date birthDayDate = value.getBirthday();
            String birthDayString = MyDateAndTimeUtil.getFormatedDateAsString(birthDayDate);
//            String message = value.getMessage ();
            String status = value.getStatus();

            if (status.equalsIgnoreCase(MessageStatusEnum.PENDING.toString())) {

                dfTblMdPending.addRow(new Object[]{
                    //"SELECT", "#", "CODE", "NAME", "SUB A/C OFFICE NO", "TELE.", "BIRTHDAY", "STATUS"
                    isSelect, keyNo, code, name, acOfficeNo, memTeleNo, birthDayString, status
                });
            } else if (status.equalsIgnoreCase(MessageStatusEnum.QUEUE.toString())) {
                dfTblMdPending.addRow(new Object[]{
                    //"SELECT", "#", "CODE", "NAME", "SUB A/C OFFICE NO", "TELE.", "BIRTHDAY", "STATUS"
                    isSelect, keyNo, code, name, acOfficeNo, memTeleNo, birthDayString, status
                });
            }

//            else if (status.equalsIgnoreCase (MessageStatusEnum.SENT.toString ()))
//            {
//
//                dfTblMdSent.addRow (new Object[]
//                {
//                    //"SELECT", "#", "CODE", "NAME", "SUB A/C OFFICE NO", "TELE.", "BIRTHDAY", "STATUS"
//                    isSelect, keyNo, code, name, acOfficeNo, memTeleNo, birthDayString, status
//                });
//            } else if (status.equalsIgnoreCase (MessageStatusEnum.UNSENT.toString ()))
//            {
//
//                dfTblMdUnsent.addRow (new Object[]
//                {
//                    //"SELECT", "#", "CODE", "NAME", "SUB A/C OFFICE NO", "TELE.", "BIRTHDAY", "STATUS"
//                    isSelect, keyNo, code, name, acOfficeNo, memTeleNo, birthDayString, status
//                });
//            } else if (status.equalsIgnoreCase (MessageStatusEnum.FAILED.toString ().trim ()))
//            {
//
//                dfTblMdUnsent.addRow (new Object[]
//                {
//                    //"SELECT", "#", "CODE", "NAME", "SUB A/C OFFICE NO", "TELE.", "BIRTHDAY", "STATUS"
//                    isSelect, keyNo, code, name, acOfficeNo, memTeleNo, birthDayString, status
//                });
//            }
        }

    }

    private void sendSms() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                if (MyMessagesUtility.showConfirmDoYouWantToRemove("Confirm ?") == 0) {

//                    --------------------------------------
                    Company_Profile.setMsgSendStart(true);
//                    --------------------------------------

                    String message = tfMessage.getText().trim();
                    if (message.isEmpty()) {
                        MyMessagesUtility.showWarning("Message is empty.");
                    } else {
                        Map<Integer, MessageToMemeberSearch_pojo> map = tableMap;
//                    Map<Integer, NewJurnal_pojo> tableMap2 = tableMap;
                        new MessageToMemebers_service().sendSms(map, message);
                    }
                }
            }
        }).start();
    }

    private void sendSms_2() {

        trdSend = new Thread(new Runnable() {
            @Override
            public void run() {

                String messageType = MyMessageTypeEnum.CUSTOM.toString().trim();
                int sentSMSCount = 0;
                int sentConfirmSMSCount = 0;

                if (MyMessagesUtility.showConfirmDoYouWantToRemove("Confirm ?") == 0) {

                    //-------------------------------------------------------        
                    trdWaiting = new Thread(new Runnable() {
                        @Override
                        public void run() {
                            waitingDialogSMSSend = new WaitingDialogSMSSend("", "Starting ...", ApplicationDesktop.appDesktop, true);
                            waitingDialogSMSSend.setVisible(true);
                        }
                    });
                    trdWaiting.start();
                    //-------------------------------------------------------

                    if (messageToMemebers_service == null) {
                        messageToMemebers_service = new MessageToMemebers_service();
                    }
                    if (sendMessage == null) {
                        sendMessage = new SendMessage();
                    }
                    // --------------------------------------------------
                    Company_Profile.setMsgSendStart(true);
                    // --------------------------------------------------

                    DefaultTableModel dfTblMd = (DefaultTableModel) tblPending.getModel();
                    int rowCount = dfTblMd.getRowCount();

                    //-------------------------------------
                    MySMSServer.restartService();
                    //-------------------------------------

                    String msg = tfMessage.getText().trim();
                    if (!msg.isEmpty()) {

                        try {
                            OutboundMessage.MessageStatuses confirmStart = sendMessage.sendConfirm_1(Company_Profile.getConfirmTeleNo(), "Message to member 2 sending start.");
                            if (!confirmStart.toString().trim().equals(MessageStatusEnum.SENT.toString().trim())) {
                                MyMessagesUtility.showWarning("Message to member 2 " + confirmStart.toString());
                            } else if (confirmStart.toString().trim().equals(MessageStatusEnum.SENT.toString().trim())) {
                                ++sentConfirmSMSCount;
                            }

                            outerLoop:
                            for (int i = currentRow; i < rowCount; i++) {

                                if (!Company_Profile.getMsgSendStart()) // IF MSG SENDING STOPED
                                {
                                    break outerLoop;
                                }

                                int j = i;
                                ++j;

                                try {
                                    Thread.sleep(500);
                                } catch (InterruptedException ex) {
                                    Logger.getLogger(Jurnal_if_view_2.class.getName()).log(Level.SEVERE, null, ex);
                                }

                                //----------------------------------------
                                String customeMessage = "On Processing : " + j + "/" + rowCount;
                                waitingDialogSMSSend.setCustomMessage(customeMessage);

                                tblPending.setRowSelectionInterval(i, i);
                                tblPending.scrollRectToVisible(new Rectangle(tblPending.getCellRect(i, 0, true)));
                                //----------------------------------------

                                Boolean isSelected = Boolean.valueOf(String.valueOf(dfTblMd.getValueAt(i, 0)));
                                if (isSelected) {
                                    if (!dfTblMd.getValueAt(i, 7).toString().trim().equalsIgnoreCase(OutboundMessage.MessageStatuses.SENT.toString())) {
//                                String voucherNo = String.valueOf (dfTblMd.getValueAt (i, 2));
//                                String cusCode = String.valueOf (dfTblMd.getValueAt (i, 3));

                                        String message = null;

                                        String cusName = String.valueOf(dfTblMd.getValueAt(i, 3));
                                        if (!cusName.isEmpty()) {
                                            String msg2 = "Dear ".concat(cusName).concat(", ");
                                            message = msg2.concat(msg);
                                        } else {
                                            message = msg;
                                        }
                                        message = message.concat(Company_Profile.getCompanyName());

                                        String phoneNo = String.valueOf(dfTblMd.getValueAt(i, 5));

// SEND
                                        OutboundMessage.MessageStatuses msgStatus = messageToMemebers_service.sendSMS_2(phoneNo, message);
                                        if (msgStatus.toString().trim().equalsIgnoreCase(OutboundMessage.MessageStatuses.SENT.toString().trim())) {
                                            ++sentSMSCount;
                                        }
                                        dfTblMd.setValueAt(msgStatus.toString(), i, 7);
                                    }

                                }
                                currentRow = i;
                            }

                            waitingDialogSMSSend.dispose();
                            trdWaiting.interrupt();

                            OutboundMessage.MessageStatuses confirmEnd = sendMessage.sendConfirm_1(Company_Profile.getConfirmTeleNo(), "Message to member 2 sending end with " + sentSMSCount + " messages.");
                            if (!confirmEnd.toString().trim().equals(MessageStatusEnum.SENT.toString().trim())) {
                                MyMessagesUtility.showWarning("Message to member 2 " + confirmEnd.toString());
                            } else if (confirmEnd.toString().trim().equals(MessageStatusEnum.SENT.toString().trim())) {
                                ++sentConfirmSMSCount;
                            }

                            new SMSCount_Service().saveSMSCount(messageType, sentSMSCount);
                            new SMSCount_Service().saveSMSCount(MyMessageTypeEnum.CONFIRM.toString().trim(), sentConfirmSMSCount);
                        } catch (Exception ex) {
                            MyMessagesUtility.showError(ex.toString());
                            Logger.getLogger(MessageToMemebers_view_in_Multicluster_2.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }

                }
            }
        });
        trdSend.start();

    }

    private void reSendSms() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                if (MyMessagesUtility.showConfirmDoYouWantToRemove("Confirm ?") == 0) {

//                    --------------------------------------
                    Company_Profile.setMsgSendStart(true);
//                    --------------------------------------

                    String message = tfMessage.getText().trim();
                    if (message.isEmpty()) {
                        MyMessagesUtility.showWarning("Message is empty.");
                    } else {
                        Map<Integer, MessageToMemeberSearch_pojo> map = tableMap;
//                    Map<Integer, NewJurnal_pojo> tableMap2 = tableMap;
                        new MessageToMemebers_service().reSendSms(map, message);
                    }
                }
            }
        }).start();
    }

    public void loadTablesByMapKey(Integer keyPara, String messageStatusStringPara) {

        Integer key = keyPara;
        String messageStatusString = messageStatusStringPara.trim();

        MessageToMemeberSearch_pojo value = tableMap.get(key);

        value.setStatus(messageStatusString);
        tableMap.remove(key);
        tableMap.put(key, value);

        loadTables();

    }

    private void close() {
        dispose();
    }

    private void clearPendingTbl() {
        //        PENDING
        final DefaultTableModel dfTblMdPending = (DefaultTableModel) tblPending.getModel();
        int rowCountPending = dfTblMdPending.getRowCount();
        for (int i = 0; i < rowCountPending; i++) {
            dfTblMdPending.removeRow(0);
        }
        dfTblMdPending.setRowCount(0);
    }

    private void showMessageInf() {

        int selectedRow = tblPending.getSelectedRow();
        String phnNo = tblPending.getValueAt(selectedRow, 5).toString().trim();
        String msg = tfMessage.getText().trim();
        String msgStutas = tblPending.getValueAt(selectedRow, 7).toString().trim();

        showMessageDetails_INF.showMessage(phnNo, msg, msgStutas);

    }

    public void closeMessageInf() {
        if (showMessageDetails_INF != null) {
            showMessageDetails_INF.dispose();
        }
    }

}
